/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as TeamRouteImport } from './routes/team'
import { Route as WorkshopRouteImport } from './routes/workshop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/backup': typeof BackupRoute
  '/clients': typeof ClientsRoute
  '/dispatch': typeof DispatchRoute
  '/finance': typeof FinanceRoute
  '/fleet': typeof FleetRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/payroll': typeof PayrollRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suppliers': typeof SuppliersRoute
  '/team': typeof TeamRoute
  '/workshop': typeof WorkshopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/backup': typeof BackupRoute
  '/clients': typeof ClientsRoute
  '/dispatch': typeof DispatchRoute
  '/finance': typeof FinanceRoute
  '/fleet': typeof FleetRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/payroll': typeof PayrollRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suppliers': typeof SuppliersRoute
  '/team': typeof TeamRoute
  '/workshop': typeof WorkshopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/backup': typeof BackupRoute
  '/clients': typeof ClientsRoute
  '/dispatch': typeof DispatchRoute
  '/finance': typeof FinanceRoute
  '/fleet': typeof FleetRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/payroll': typeof PayrollRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suppliers': typeof SuppliersRoute
  '/team': typeof TeamRoute
  '/workshop': typeof WorkshopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/backup'
    | '/clients'
    | '/dispatch'
    | '/finance'
    | '/fleet'
    | '/ledger'
    | '/login'
    | '/operations'
    | '/payroll'
    | '/reset-password'
    | '/suppliers'
    | '/team'
    | '/workshop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/backup'
    | '/clients'
    | '/dispatch'
    | '/finance'
    | '/fleet'
    | '/ledger'
    | '/login'
    | '/operations'
    | '/payroll'
    | '/reset-password'
    | '/suppliers'
    | '/team'
    | '/workshop'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/backup'
    | '/clients'
    | '/dispatch'
    | '/finance'
    | '/fleet'
    | '/ledger'
    | '/login'
    | '/operations'
    | '/payroll'
    | '/reset-password'
    | '/suppliers'
    | '/team'
    | '/workshop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BackupRoute: typeof BackupRoute
  ClientsRoute: typeof ClientsRoute
  DispatchRoute: typeof DispatchRoute
  FinanceRoute: typeof FinanceRoute
  FleetRoute: typeof FleetRoute
  LedgerRoute: typeof LedgerRoute
  LoginRoute: typeof LoginRoute
  OperationsRoute: typeof OperationsRoute
  PayrollRoute: typeof PayrollRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuppliersRoute: typeof SuppliersRoute
  TeamRoute: typeof TeamRoute
  WorkshopRoute: typeof WorkshopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BackupRoute: BackupRoute,
  ClientsRoute: ClientsRoute,
  DispatchRoute: DispatchRoute,
  FinanceRoute: FinanceRoute,
  FleetRoute: FleetRoute,
  LedgerRoute: LedgerRoute,
  LoginRoute: LoginRoute,
  OperationsRoute: OperationsRoute,
  PayrollRoute: PayrollRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuppliersRoute: SuppliersRoute,
  TeamRoute: TeamRoute,
  WorkshopRoute: WorkshopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
